version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  groups:
    github-actions:
      patterns:
        - "*"
- package-ecosystem: docker
  directories:
    - "/sandbox"
    - "/sandbox-browser"
    - "/sandbox-common"
  schedule:
    interval: daily
  groups:
    docker:
      patterns:
        - "*"